### ISSUE TITLE
Bottom decile has sign flipped on relative impact

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-api#1603]
For example this case has positive [absolute](https://policyengine.org/us/policy?focus=policyOutput.distributionalImpact.incomeDecile.average&household=41543&region=enhanced_us&timePeriod=2024&baseline=2&reform=60014) change:
<img width="886" alt="image" src="https://github.com/PolicyEngine/policyengine-api/assets/6076111/e81e588e-bcb5-404a-80a6-a9b2ae45641f">

but negative relative:
<img width="895" alt="image" src="https://github.com/PolicyEngine/policyengine-api/assets/6076111/6dd71f79-d3cd-4b1b-8482-c8eccf31c76b">

This shouldn't happen since we assign negatives to the -1 decile: https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/variables/household/income/household/household_income_decile.py

And we use that for binning:

https://github.com/PolicyEngine/policyengine-api/blob/615a196708cf42197002928e3a660e6ed7c11d08/policyengine_api/endpoints/economy/compare.py#L125-L158

**Comment by anth-volk** [comment]
This might be driven by enhanced CPS simulation runs only. For example:
[with enhanced CPS](https://policyengine.org/us/policy?reform=62362&focus=policyOutput.distributionalImpact.incomeDecile.relative&region=enhanced_us&timePeriod=2024&baseline=2)
[without](https://policyengine.org/us/policy?reform=62362&focus=policyOutput.distributionalImpact.incomeDecile.relative&region=us&timePeriod=2024&baseline=2)

The problem only occurs with. I'm not sure if this is true throughout, but this may be the driving factor.

**Comment by anth-volk** [comment]
Also true for the original policy posted in this PR (https://policyengine.org/us/policy?focus=policyOutput.distributionalImpact.incomeDecile.relative&household=41543&region=enhanced_us&timePeriod=2024&baseline=2&reform=60014)

**Comment by anth-volk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Relative impacts not displaying correctly](https://trello.com/c/VoGrwi6b/9-relative-impacts-not-displaying-correctly)

**Comment by anth-volk** [comment]
I have gotten about as far as I can on this. This has become a major time sink, as the errors that are occurring here are incredibly strange.

First, here's a list of what isn't causing the issue:
* The US package
* Core
* MicroDF
* Numpy
* Pandas
* Versioning (core, US, Python, Numpy, or Pandas)
* Microdata assignment of values when loading a dataset (at least I think)

About half of the issue emerges from https://github.com/PolicyEngine/policyengine-api/blob/18472a62306a57609a9ce227c18e97642d744e14/policyengine_api/endpoints/economy/single_economy.py#L141. This function computes various values for a given economy, and on the relevant line, we clip `household_income_decile` to a value between 1 and 10. Instead of dropping out households with negative incomes (that have decile values of -1), this code actually just changes all their values to 1, thereby undoing what the US package does.

However, this is not the entire error. Even after removing the `clip` line, something in the code changes the value of -1 deciles to 1. Somewhere between the completion of https://github.com/PolicyEngine/policyengine-api/blob/18472a62306a57609a9ce227c18e97642d744e14/policyengine_api/endpoints/economy/reform_impact.py#L158 and the beginning of https://github.com/PolicyEngine/policyengine-api/blob/18472a62306a57609a9ce227c18e97642d744e14/policyengine_api/endpoints/economy/reform_impact.py#L175, something in the code makes this change. My guess is that it has something to do with the `else` block beginning at https://github.com/PolicyEngine/policyengine-api/blob/18472a62306a57609a9ce227c18e97642d744e14/policyengine_api/endpoints/economy/reform_impact.py#L101. Prior to this block, I have confirmation that we have the correct number of negative deciles if we remove the `clip` line mentioned previously. However, by the time we reach https://github.com/PolicyEngine/policyengine-api/blob/18472a62306a57609a9ce227c18e97642d744e14/policyengine_api/endpoints/economy/reform_impact.py#L175, the -1 deciles have become +1, and we have again lost the ability to filter out negative households.

More broadly, navigating through the API's code and trying to diagnose errors has been trying, to say the least. The repo structure does not follow MVC standards, quite a bit of the code is just imperative, and functions nest in strange ways that make it difficult to determine where anything might be located. It's also very difficult to follow some functions' naming conventions, though the top-level endpoints and broader controller functions do make sense.

**Comment by anth-volk** [comment]
As an update, dumping the local database recalculates the baseline policy, which may be sufficient to allow the code to at least handle -1 deciles at the above point. However, the output given by the API is zeros across the board. It's unclear yet if that's because the `decile_impact` code doesn't filter out -1 deciles yet, or something else.

**Comment by anth-volk** [comment]
Removing -1's within `decile_impact` fixed all outputs except `decile_impact` itself, where the chart's showing a -1 decile. Let me do some cleaning up and a couple minor fixes on `decile_impact` and the open PR will be good to go.
