### ISSUE TITLE
Hash user IDs

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-api#805]
For privacy, so people can't page through households by guessing a number

**Comment by ken1009us** [comment]
I would like to solve this problem and have already created the branch to fix this but I got a permission error. I wonder are we allowed to solve issues for this project? I also would like to ask about the db credentials. Thank you!

**Comment by MaxGhenis** [comment]
Thanks! Please file a PR from your fork.

**Comment by lilychen0505** [comment]
After reviewing the code, I've realized that using hashing for the household_id may not be feasible. This is because hashing is a one-way process, designed for ensuring data integrity and security, and does not support reversible encoding/decoding. To address this, I suggest we consider symmetric encryption algorithms like AES (Advanced Encryption Standard). We could also think about using JWT, although it might not be ideal due to the potential for token expiration within a certain timeframe.

**Comment by nikhilwoodruff** [comment]
@MaxGhenis I agree with @lilychen0505 here. Also it doesn't actually add any privacy outside of just obfuscation because someone could just look at which hashing function we use and page through the household ID numbers and then go to the hashed household IDs. So I think we should close this issue- feel free to reopen though if we're after obfuscation.
